version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: django/Dockerfile
    command: gunicorn a_core.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./django/:/app/
      - static_volume:/app/static
      - media_volume:/app/media
    env_file:
      - ./django/.env
    networks:
      - backend-network
    environment:
      - DJANGO_SETTINGS_MODULE=a_core.settings.product
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M

  nginx:
    image: nginx:1.21-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./django/static:/app/static
      - ./django/media:/app/media
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - web
    networks:
      - backend-network

volumes:
  static_volume:
  media_volume:

networks:
  backend-network:
    driver: bridge 