# Generated by Django 5.1.6 on 2025-04-14 19:28

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("a_apis", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email", models.EmailField(max_length=254)),
                ("verification_code", models.CharField(max_length=6)),
                ("is_verified", models.BooleanField(default=False)),
                ("expires_at", models.DateTimeField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EupmyeondongRegion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=20, verbose_name="읍면동명")),
                (
                    "code",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="읍면동 코드"
                    ),
                ),
                (
                    "region_polygon",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        help_text="행정구역의 경계를 이루는 다각형 좌표들",
                        null=True,
                        srid=4326,
                        verbose_name="읍면동 영역",
                    ),
                ),
                (
                    "center_coordinates",
                    django.contrib.gis.db.models.fields.PointField(
                        help_text="행정구역의 중심점 좌표",
                        null=True,
                        srid=4326,
                        verbose_name="중심 좌표",
                    ),
                ),
            ],
            options={
                "verbose_name": "읍면동",
                "verbose_name_plural": "읍면동 목록",
                "db_table": "regions_eupmyeondong",
            },
        ),
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "file",
                    models.FileField(upload_to="files/%Y/%m/%d/", verbose_name="파일"),
                ),
                ("size", models.BigIntegerField(verbose_name="파일 크기")),
                (
                    "type",
                    models.CharField(max_length=50, verbose_name="파일 타입(확장자)"),
                ),
            ],
            options={
                "verbose_name": "파일",
                "verbose_name_plural": "파일 목록",
                "db_table": "files",
            },
        ),
        migrations.CreateModel(
            name="InterestProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "관심 상품",
                "verbose_name_plural": "관심 상품 목록",
                "db_table": "interest_products",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=100, verbose_name="상품 제목")),
                (
                    "trade_type",
                    models.CharField(
                        choices=[("sale", "판매하기"), ("share", "나눔하기")],
                        default="sale",
                        max_length=10,
                        verbose_name="거래 방식",
                    ),
                ),
                (
                    "price",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="판매 금액"
                    ),
                ),
                (
                    "accept_price_offer",
                    models.BooleanField(default=False, verbose_name="가격 제안 허용"),
                ),
                ("description", models.TextField(verbose_name="상품 설명")),
                (
                    "meeting_location",
                    django.contrib.gis.db.models.fields.PointField(
                        null=True, srid=4326, verbose_name="거래 희망 위치"
                    ),
                ),
                (
                    "location_description",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="거래 위치 설명",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "판매중"),
                            ("reserved", "예약중"),
                            ("soldout", "판매완료"),
                        ],
                        default="new",
                        max_length=10,
                        verbose_name="상품 상태",
                    ),
                ),
                (
                    "view_count",
                    models.PositiveIntegerField(default=0, verbose_name="조회수"),
                ),
                (
                    "refresh_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="끌어올린 시간"
                    ),
                ),
            ],
            options={
                "verbose_name": "상품",
                "verbose_name_plural": "상품 목록",
                "db_table": "products",
                "ordering": ["-refresh_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "상품 이미지",
                "verbose_name_plural": "상품 이미지 목록",
                "db_table": "product_images",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="SidoRegion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=20, verbose_name="시도명")),
                (
                    "code",
                    models.CharField(
                        max_length=2, unique=True, verbose_name="시도 코드"
                    ),
                ),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        help_text="시도 행정구역의 경계 좌표",
                        null=True,
                        srid=4326,
                        verbose_name="행정구역 경계",
                    ),
                ),
            ],
            options={
                "verbose_name": "시도",
                "verbose_name_plural": "시도 목록",
                "db_table": "regions_sido",
            },
        ),
        migrations.CreateModel(
            name="SigunguRegion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=20, verbose_name="시군구명")),
                (
                    "code",
                    models.CharField(
                        max_length=5, unique=True, verbose_name="시군구 코드"
                    ),
                ),
            ],
            options={
                "verbose_name": "시군구",
                "verbose_name_plural": "시군구 목록",
                "db_table": "regions_sigungu",
            },
        ),
        migrations.CreateModel(
            name="UserActivityRegion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "priority",
                    models.IntegerField(
                        default=1,
                        help_text="1: 대표 동네, 2: 두번째 동네, 3: 세번째 동네",
                        verbose_name="동네 순서",
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="최초 인증 일시"
                    ),
                ),
                (
                    "last_verified_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="마지막 인증 일시"
                    ),
                ),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        null=True, srid=4326, verbose_name="인증 위치"
                    ),
                ),
            ],
            options={
                "verbose_name": "사용자 활동지역",
                "verbose_name_plural": "사용자 활동지역 목록",
                "db_table": "user_activity_regions",
            },
        ),
    ]
