# Generated by Django 5.1.6 on 2025-04-14 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("a_apis", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="interestproduct",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interest_products",
                to=settings.AUTH_USER_MODEL,
                verbose_name="사용자",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to=settings.AUTH_USER_MODEL,
                verbose_name="판매자",
            ),
        ),
        migrations.AddField(
            model_name="interestproduct",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interested_users",
                to="a_apis.product",
                verbose_name="관심 상품",
            ),
        ),
        migrations.AddField(
            model_name="productimage",
            name="file",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_images",
                to="a_apis.file",
                verbose_name="이미지 파일",
            ),
        ),
        migrations.AddField(
            model_name="productimage",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="a_apis.product",
                verbose_name="상품",
            ),
        ),
        migrations.AddField(
            model_name="sigunguregion",
            name="sido",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sigungus",
                to="a_apis.sidoregion",
            ),
        ),
        migrations.AddField(
            model_name="eupmyeondongregion",
            name="sigungu",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="eupmyeondongs",
                to="a_apis.sigunguregion",
            ),
        ),
        migrations.AddField(
            model_name="useractivityregion",
            name="activity_area",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_activities",
                to="a_apis.eupmyeondongregion",
                verbose_name="활동지역",
            ),
        ),
        migrations.AddField(
            model_name="useractivityregion",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity_regions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="interestproduct",
            unique_together={("user", "product")},
        ),
        migrations.AddConstraint(
            model_name="useractivityregion",
            constraint=models.UniqueConstraint(
                fields=("user", "priority"), name="unique_user_priority"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="useractivityregion",
            unique_together={("user", "activity_area")},
        ),
    ]
