# Generated by Django 5.1.6 on 2025-05-07 20:43

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("a_apis", "0006_product_buyer_product_completed_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MannerRatingType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, verbose_name="평가명")),
                (
                    "is_positive",
                    models.BooleanField(default=True, verbose_name="긍정 평가 여부"),
                ),
                (
                    "score_delta",
                    models.FloatField(default=0.1, verbose_name="점수 변화량"),
                ),
            ],
            options={
                "verbose_name": "매너 평가 유형",
                "verbose_name_plural": "매너 평가 유형 목록",
                "db_table": "manner_rating_types",
                "ordering": ["-is_positive", "name"],
            },
        ),
        migrations.CreateModel(
            name="PriceOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("price", models.PositiveIntegerField(verbose_name="제안 가격")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "대기중"),
                            ("accepted", "수락됨"),
                            ("rejected", "거절됨"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="상태",
                    ),
                ),
                (
                    "responded_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="응답 일시"
                    ),
                ),
                (
                    "chat_room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="apis_price_offers",
                        to="a_apis.chatroom",
                        verbose_name="채팅방",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="apis_price_offers",
                        to="a_apis.product",
                        verbose_name="상품",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="apis_price_offers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="제안자",
                    ),
                ),
            ],
            options={
                "verbose_name": "가격 제안",
                "verbose_name_plural": "가격 제안 목록",
                "db_table": "apis_price_offers",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Trade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "final_price",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="최종 거래 가격"
                    ),
                ),
                (
                    "reviewed_by_seller",
                    models.BooleanField(
                        default=False, verbose_name="판매자 리뷰 작성 여부"
                    ),
                ),
                (
                    "reviewed_by_buyer",
                    models.BooleanField(
                        default=False, verbose_name="구매자 리뷰 작성 여부"
                    ),
                ),
                (
                    "seller_manner_rated",
                    models.BooleanField(
                        default=False, verbose_name="판매자 매너 평가 작성 여부"
                    ),
                ),
                (
                    "buyer_manner_rated",
                    models.BooleanField(
                        default=False, verbose_name="구매자 매너 평가 작성 여부"
                    ),
                ),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bought_trades",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="구매자",
                    ),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trade",
                        to="a_apis.product",
                        verbose_name="상품",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sold_trades",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="판매자",
                    ),
                ),
            ],
            options={
                "verbose_name": "거래",
                "verbose_name_plural": "거래 목록",
                "db_table": "trades",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TradeAppointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "appointment_date",
                    models.DateTimeField(verbose_name="약속 날짜 및 시간"),
                ),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        srid=4326, verbose_name="약속 장소"
                    ),
                ),
                (
                    "location_description",
                    models.CharField(max_length=200, verbose_name="약속 장소 설명"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "대기중"),
                            ("confirmed", "확정됨"),
                            ("canceled", "취소됨"),
                            ("completed", "완료됨"),
                        ],
                        default="pending",
                        max_length=15,
                        verbose_name="약속 상태",
                    ),
                ),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buyer_appointments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="구매자",
                    ),
                ),
                (
                    "chat_room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="a_apis.chatroom",
                        verbose_name="채팅방",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="a_apis.product",
                        verbose_name="상품",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seller_appointments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="판매자",
                    ),
                ),
            ],
            options={
                "verbose_name": "거래 약속",
                "verbose_name_plural": "거래 약속 목록",
                "db_table": "trade_appointments",
                "ordering": ["-appointment_date"],
            },
        ),
        migrations.CreateModel(
            name="MannerRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "rating_type",
                    models.CharField(
                        choices=[("positive", "긍정적"), ("negative", "부정적")],
                        max_length=10,
                        verbose_name="평가 유형",
                    ),
                ),
                ("tags", models.JSONField(default=list, verbose_name="평가 태그")),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="추가 코멘트"),
                ),
                (
                    "rated_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="apis_received_ratings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="평가 대상자",
                    ),
                ),
                (
                    "rater",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="apis_given_ratings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="평가자",
                    ),
                ),
                (
                    "trade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manner_ratings",
                        to="a_apis.trade",
                        verbose_name="거래",
                    ),
                ),
            ],
            options={
                "verbose_name": "매너 평가",
                "verbose_name_plural": "매너 평가 목록",
                "db_table": "apis_manner_ratings",
                "ordering": ["-created_at"],
                "unique_together": {("trade", "rater", "rated_user")},
            },
        ),
        migrations.CreateModel(
            name="TradeReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("content", models.TextField(verbose_name="내용")),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="apis_received_reviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="대상자",
                    ),
                ),
                (
                    "trade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="a_apis.trade",
                        verbose_name="거래",
                    ),
                ),
                (
                    "writer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="apis_written_reviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="작성자",
                    ),
                ),
            ],
            options={
                "verbose_name": "거래 후기",
                "verbose_name_plural": "거래 후기 목록",
                "db_table": "apis_trade_reviews",
                "ordering": ["-created_at"],
                "unique_together": {("trade", "writer")},
            },
        ),
    ]
