# Generated by Django 5.1.6 on 2025-05-13 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("a_apis", "0007_mannerratingtype_priceoffer_trade_tradeappointment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="region",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="a_apis.eupmyeondongregion",
                verbose_name="등록 동네",
            ),
        ),
    ]
