# Generated by Django 5.1.6 on 2025-06-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("a_apis", "0008_product_region"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[
                    ("selling", "판매중"),
                    ("reserved", "예약중"),
                    ("soldout", "판매완료"),
                ],
                default="selling",
                max_length=10,
                verbose_name="상품 상태",
            ),
        ),
    ]
