# Generated by Django 5.1.6 on 2025-04-30 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("a_apis", "0006_product_buyer_product_completed_at_and_more"),
        ("a_user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="rating_count",
            field=models.PositiveIntegerField(default=0, verbose_name="매너 평가 횟수"),
        ),
        migrations.CreateModel(
            name="PriceOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("price", models.PositiveIntegerField(verbose_name="제안 가격")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "대기중"),
                            ("accepted", "수락됨"),
                            ("rejected", "거절됨"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="상태",
                    ),
                ),
                (
                    "chat_room",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_offers",
                        to="a_apis.chatroom",
                        verbose_name="채팅방",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_offers",
                        to="a_apis.product",
                        verbose_name="상품",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_offers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="제안자",
                    ),
                ),
            ],
            options={
                "verbose_name": "가격 제안",
                "verbose_name_plural": "가격 제안 목록",
                "db_table": "price_offers",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MannerRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "rating_type",
                    models.CharField(
                        choices=[
                            ("time", "시간 약속을 잘 지켜요"),
                            ("response", "응답이 빨라요"),
                            ("kind", "친절하고 매너가 좋아요"),
                            ("accurate", "상품 상태가 설명과 일치해요"),
                            ("negotiable", "가격 제안에 대해 긍정적이에요"),
                            ("bad_time", "약속시간을 안 지켜요"),
                            ("bad_response", "응답이 느려요"),
                            ("bad_manner", "불친절해요"),
                            ("bad_accuracy", "상품 상태가 설명과 달라요"),
                            ("bad_price", "가격 흥정이 너무 심해요"),
                        ],
                        max_length=20,
                        verbose_name="평가 유형",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manner_ratings",
                        to="a_apis.product",
                        verbose_name="상품",
                    ),
                ),
                (
                    "rated_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_ratings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="피평가자",
                    ),
                ),
                (
                    "rater",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="given_ratings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="평가자",
                    ),
                ),
            ],
            options={
                "verbose_name": "매너 평가",
                "verbose_name_plural": "매너 평가 목록",
                "db_table": "manner_ratings",
                "ordering": ["-created_at"],
                "unique_together": {("product", "rater", "rating_type")},
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("content", models.TextField(verbose_name="후기 내용")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="a_apis.product",
                        verbose_name="상품",
                    ),
                ),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_reviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="수신자",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="written_reviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="작성자",
                    ),
                ),
            ],
            options={
                "verbose_name": "거래 후기",
                "verbose_name_plural": "거래 후기 목록",
                "db_table": "reviews",
                "ordering": ["-created_at"],
                "unique_together": {("product", "reviewer")},
            },
        ),
    ]
