name: Deploy to Server

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  deploy:
    # develop 브랜치에서 main 브랜치로 머지된 PR이 닫혔을 때만 실행
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main')
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: ${{ secrets.AWS_SSH_PORT }}
        script: |
            # 프로젝트 디렉토리로 이동
            cd ~/${{ github.event.repository.name }}
            
            # 작업 중인 변경사항 있으면 임시 저장
            git stash
            
            # 메인 브랜치로 전환하고 최신 코드 가져오기
            git switch main
            git pull origin main
            
            # 디스크 사용량 확인 및 기록 (배포 전)
            echo "Disk usage before cleanup: $(date)" >> deploy_disk_usage.log
            df -h / >> deploy_disk_usage.log
            
            # 리소스 정리 (사용하지 않는 이미지와 볼륨만 삭제)
            echo "Cleaning unused Docker resources..."
            docker system prune -f --filter "until=24h"
            
            # 웹 컨테이너 실행 상태 확인
            CONTAINER_RUNNING=$(docker ps -q -f name=web)
            if [ -n "$CONTAINER_RUNNING" ]; then
              echo "Web container is running, stopping it first..."
              docker stop $(docker ps -q -f name=web)
              docker rm $(docker ps -aq -f name=web)
            fi
            
            # 새 이미지 빌드
            echo "Building new image for web service..."
            docker compose build web
            
            # 웹 서비스 시작
            echo "Starting web service..."
            docker compose up -d web
            
            # 서비스 상태 확인
            echo "Deployment completed at $(date)"
            docker compose ps
            
            # 마이그레이션 로그 확인
            echo "Checking migration logs..."
            docker compose logs --tail=20 web | grep -i migrat